import { createElement } from "react";
import {
  // people & faces
  UserRound,
  UsersRound,
  Smile,
  Laugh,
  ThumbsUp,
  Hand,
  Baby,
  Glasses,
  Drama,
  Bot,
  Ghost,
  Skull,
  WandSparkles,
  PartyPopper,
  // animals
  Cat,
  Dog,
  Rabbit,
  Bird,
  Fish,
  Turtle,
  Squirrel,
  Snail,
  Panda,
  PawPrint,
  Bug,
  Worm,
  Rat,
  Bone,
  Shell,
  Feather,
  // nature & weather
  Sun,
  CloudSun,
  Moon,
  Star,
  Sparkles,
  Rainbow,
  Cloud,
  Snowflake,
  Flame,
  Zap,
  Droplet,
  Droplets,
  Waves,
  Mountain,
  MountainSnow,
  TreeDeciduous,
  TreePine,
  Trees,
  TreePalm,
  Flower2,
  Leaf,
  Clover,
  Sprout,
  Gem,
  Diamond,
  // food & treats
  Apple,
  Cherry,
  Grape,
  Banana,
  Carrot,
  Citrus,
  Wheat,
  Egg,
  Salad,
  Soup,
  Sandwich,
  Hamburger,
  Pizza,
  Drumstick,
  IceCreamCone,
  IceCream2,
  Candy,
  CandyCane,
  Cookie,
  Cake,
  CakeSlice,
  Donut,
  Croissant,
  Popcorn,
  Milk,
  Coffee,
  CupSoda,
  // home & chores
  Bed,
  BedDouble,
  AlarmClock,
  Bath,
  ShowerHead,
  Utensils,
  CookingPot,
  ShoppingCart,
  ShoppingBag,
  Store,
  Trash2,
  Recycle,
  Brush,
  Paintbrush,
  Shirt,
  WashingMachine,
  Sofa,
  Lamp,
  LampDesk,
  Lightbulb,
  Plug,
  Wrench,
  Hammer,
  Drill,
  Shovel,
  Axe,
  Key,
  DoorOpen,
  Refrigerator,
  Microwave,
  // school & creative
  Backpack,
  BookOpen,
  Library,
  Pencil,
  Pen,
  NotebookPen,
  Notebook,
  GraduationCap,
  Calculator,
  FlaskConical,
  Atom,
  Microscope,
  Telescope,
  Languages,
  Globe,
  Palette,
  Ruler,
  Scissors,
  Music,
  Guitar,
  Piano,
  Drum,
  Mic,
  Radio,
  Headphones,
  Film,
  Clapperboard,
  // play & sports
  Gamepad2,
  Joystick,
  Dices,
  Puzzle,
  Trophy,
  Medal,
  Award,
  Target,
  Flag,
  Volleyball,
  Dumbbell,
  Bike,
  Footprints,
  Tent,
  Compass,
  Map,
  // getting around
  Rocket,
  Plane,
  Sailboat,
  Ship,
  TrainFront,
  Bus,
  Car,
  Truck,
  Tractor,
  Anchor,
  Umbrella,
  MapPin,
  // rewards, money & tech
  Gift,
  Ticket,
  Coins,
  Banknote,
  PiggyBank,
  DollarSign,
  CreditCard,
  Wallet,
  Tv,
  Smartphone,
  Tablet,
  Laptop,
  Watch,
  Camera,
  Clock,
  Timer,
  Hourglass,
  CalendarDays,
  Bell,
  Mail,
  MessageCircle,
  Image,
  Video,
  Sticker,
  Shapes,
  // extras
  Heart,
  Crown,
  HandHelping,
  Handshake,
  HelpCircle,
  // expanded library
  SmilePlus,
  Meh,
  Sparkle,
  PersonStanding,
  FishSymbol,
  Origami,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudDrizzle,
  CloudFog,
  Wind,
  Tornado,
  Sunrise,
  Sunset,
  MoonStar,
  Earth,
  Flower,
  Beef,
  Ham,
  Lollipop,
  Dessert,
  Bean,
  Nut,
  EggFried,
  GlassWater,
  Hexagon,
  Bookmark,
  BookCopy,
  FileText,
  PencilRuler,
  Eraser,
  Highlighter,
  Stamp,
  PenTool,
  Sigma,
  Pi,
  Beaker,
  TestTube,
  Dna,
  Magnet,
  Orbit,
  Binary,
  Speaker,
  Disc3,
  AudioLines,
  Music2,
  SpellCheck,
  Armchair,
  Fan,
  Thermometer,
  SprayCan,
  PaintRoller,
  Pickaxe,
  Construction,
  HardHat,
  BatteryFull,
  Blinds,
  DoorClosed,
  KeyRound,
  Grid2x2,
  Bolt,
  Goal,
  Shield,
  Sword,
  Swords,
  Castle,
  Crosshair,
  Gamepad,
  Spade,
  Club,
  Bomb,
  Wand,
  Send,
  FerrisWheel,
  CarFront,
  CarTaxiFront,
  Ambulance,
  Caravan,
  Forklift,
  BusFront,
  TramFront,
  PlaneTakeoff,
  Fuel,
  TrafficCone,
  TrainTrack,
  Monitor,
  MonitorPlay,
  Disc,
  Printer,
  Mouse,
  Keyboard,
  Wifi,
  Megaphone,
  ThumbsDown,
  CircleCheckBig,
  StarHalf,
  Infinity as InfinityIcon,
  Hash,
  AtSign,
  Lock,
  LockOpen,
  type LucideIcon,
} from "lucide-react";

interface IconDef {
  label: string;
  Icon: LucideIcon;
}

/** Every key in `lib/icons` must have an entry here (verified by a unit test). */
const ICONS: Record<string, IconDef> = {
  // People & faces
  person: { label: "Person", Icon: UserRound },
  people: { label: "People", Icon: UsersRound },
  smile: { label: "Smiley", Icon: Smile },
  laugh: { label: "Laughing", Icon: Laugh },
  thumbsup: { label: "Thumbs up", Icon: ThumbsUp },
  wave: { label: "Wave", Icon: Hand },
  baby: { label: "Baby", Icon: Baby },
  glasses: { label: "Glasses", Icon: Glasses },
  drama: { label: "Theatre", Icon: Drama },
  robot: { label: "Robot", Icon: Bot },
  ghost: { label: "Ghost", Icon: Ghost },
  skull: { label: "Skull", Icon: Skull },
  magic: { label: "Magic wand", Icon: WandSparkles },
  party: { label: "Party", Icon: PartyPopper },

  // Animals
  cat: { label: "Cat", Icon: Cat },
  dog: { label: "Dog", Icon: Dog },
  rabbit: { label: "Rabbit", Icon: Rabbit },
  bird: { label: "Bird", Icon: Bird },
  fish: { label: "Fish", Icon: Fish },
  turtle: { label: "Turtle", Icon: Turtle },
  squirrel: { label: "Squirrel", Icon: Squirrel },
  snail: { label: "Snail", Icon: Snail },
  panda: { label: "Panda", Icon: Panda },
  paw: { label: "Paw print", Icon: PawPrint },
  pet: { label: "Feed pet", Icon: PawPrint },
  bug: { label: "Bug", Icon: Bug },
  worm: { label: "Worm", Icon: Worm },
  rat: { label: "Mouse", Icon: Rat },
  bone: { label: "Bone", Icon: Bone },
  shell: { label: "Shell", Icon: Shell },
  feather: { label: "Feather", Icon: Feather },

  // Nature & weather
  sun: { label: "Sun", Icon: Sun },
  cloudsun: { label: "Sunny", Icon: CloudSun },
  moon: { label: "Moon", Icon: Moon },
  star: { label: "Star", Icon: Star },
  sparkles: { label: "Sparkles", Icon: Sparkles },
  rainbow: { label: "Rainbow", Icon: Rainbow },
  cloud: { label: "Cloud", Icon: Cloud },
  snowflake: { label: "Snowflake", Icon: Snowflake },
  flame: { label: "Flame", Icon: Flame },
  zap: { label: "Lightning", Icon: Zap },
  droplet: { label: "Droplet", Icon: Droplet },
  waves: { label: "Waves", Icon: Waves },
  mountain: { label: "Mountain", Icon: Mountain },
  mountainsnow: { label: "Snowy peak", Icon: MountainSnow },
  tree: { label: "Tree", Icon: TreeDeciduous },
  pine: { label: "Pine tree", Icon: TreePine },
  trees: { label: "Forest", Icon: Trees },
  palm: { label: "Palm tree", Icon: TreePalm },
  flower: { label: "Flower", Icon: Flower2 },
  leaf: { label: "Leaf", Icon: Leaf },
  clover: { label: "Clover", Icon: Clover },
  sprout: { label: "Plant", Icon: Sprout },
  gem: { label: "Gem", Icon: Gem },
  diamond: { label: "Diamond", Icon: Diamond },

  // Food & treats
  apple: { label: "Apple", Icon: Apple },
  cherry: { label: "Cherries", Icon: Cherry },
  grape: { label: "Grapes", Icon: Grape },
  banana: { label: "Banana", Icon: Banana },
  carrot: { label: "Carrot", Icon: Carrot },
  citrus: { label: "Orange", Icon: Citrus },
  wheat: { label: "Wheat", Icon: Wheat },
  egg: { label: "Egg", Icon: Egg },
  salad: { label: "Salad", Icon: Salad },
  soup: { label: "Soup", Icon: Soup },
  sandwich: { label: "Sandwich", Icon: Sandwich },
  hamburger: { label: "Burger", Icon: Hamburger },
  pizza: { label: "Pizza", Icon: Pizza },
  drumstick: { label: "Chicken", Icon: Drumstick },
  icecream: { label: "Ice cream", Icon: IceCreamCone },
  icecream2: { label: "Ice cream cup", Icon: IceCream2 },
  candy: { label: "Candy", Icon: Candy },
  candycane: { label: "Candy cane", Icon: CandyCane },
  cookie: { label: "Cookie", Icon: Cookie },
  cake: { label: "Cake", Icon: Cake },
  cakeslice: { label: "Slice of cake", Icon: CakeSlice },
  donut: { label: "Donut", Icon: Donut },
  croissant: { label: "Croissant", Icon: Croissant },
  popcorn: { label: "Popcorn", Icon: Popcorn },
  milk: { label: "Milk", Icon: Milk },
  cocoa: { label: "Hot cocoa", Icon: Coffee },
  soda: { label: "Soda", Icon: CupSoda },

  // Home & chores
  bed: { label: "Make bed", Icon: Bed },
  beddouble: { label: "Bedtime", Icon: BedDouble },
  alarm: { label: "Wake up", Icon: AlarmClock },
  bath: { label: "Bath", Icon: Bath },
  shower: { label: "Shower", Icon: ShowerHead },
  dishes: { label: "Dishes", Icon: Utensils },
  cook: { label: "Cook", Icon: CookingPot },
  groceries: { label: "Groceries", Icon: ShoppingCart },
  shopbag: { label: "Shopping", Icon: ShoppingBag },
  store: { label: "Store", Icon: Store },
  trash: { label: "Take out trash", Icon: Trash2 },
  recycle: { label: "Recycling", Icon: Recycle },
  clean: { label: "Clean", Icon: Brush },
  paint: { label: "Paint", Icon: Paintbrush },
  laundry: { label: "Laundry", Icon: Shirt },
  washer: { label: "Washing machine", Icon: WashingMachine },
  tidy: { label: "Tidy up", Icon: Sofa },
  lamp: { label: "Lamp", Icon: Lamp },
  desklamp: { label: "Desk", Icon: LampDesk },
  lightbulb: { label: "Lightbulb", Icon: Lightbulb },
  plug: { label: "Plug", Icon: Plug },
  plants: { label: "Water plants", Icon: Droplets },
  yard: { label: "Yard work", Icon: Leaf },
  fix: { label: "Fix it", Icon: Wrench },
  build: { label: "Build", Icon: Hammer },
  drill: { label: "Drill", Icon: Drill },
  shovel: { label: "Dig", Icon: Shovel },
  axe: { label: "Chop", Icon: Axe },
  key: { label: "Keys", Icon: Key },
  door: { label: "Door", Icon: DoorOpen },
  fridge: { label: "Fridge", Icon: Refrigerator },
  microwave: { label: "Microwave", Icon: Microwave },

  // School & creative
  backpack: { label: "Pack bag", Icon: Backpack },
  book: { label: "Reading", Icon: BookOpen },
  library: { label: "Library", Icon: Library },
  homework: { label: "Homework", Icon: Pencil },
  pen: { label: "Pen", Icon: Pen },
  notes: { label: "Notes", Icon: NotebookPen },
  notebook: { label: "Notebook", Icon: Notebook },
  study: { label: "Study", Icon: GraduationCap },
  math: { label: "Math", Icon: Calculator },
  science: { label: "Science", Icon: FlaskConical },
  atom: { label: "Atom", Icon: Atom },
  microscope: { label: "Microscope", Icon: Microscope },
  telescope: { label: "Telescope", Icon: Telescope },
  languages: { label: "Languages", Icon: Languages },
  globe: { label: "Globe", Icon: Globe },
  palette: { label: "Art", Icon: Palette },
  ruler: { label: "Ruler", Icon: Ruler },
  scissors: { label: "Scissors", Icon: Scissors },
  music: { label: "Music", Icon: Music },
  guitar: { label: "Guitar", Icon: Guitar },
  piano: { label: "Piano", Icon: Piano },
  drum: { label: "Drums", Icon: Drum },
  mic: { label: "Sing", Icon: Mic },
  radio: { label: "Radio", Icon: Radio },
  headphones: { label: "Headphones", Icon: Headphones },
  movie: { label: "Movie", Icon: Film },
  clapperboard: { label: "Movies", Icon: Clapperboard },

  // Play & sports
  game: { label: "Game time", Icon: Gamepad2 },
  joystick: { label: "Arcade", Icon: Joystick },
  dice: { label: "Board game", Icon: Dices },
  puzzle: { label: "Puzzle", Icon: Puzzle },
  trophy: { label: "Trophy", Icon: Trophy },
  medal: { label: "Medal", Icon: Medal },
  award: { label: "Award", Icon: Award },
  target: { label: "Target", Icon: Target },
  flag: { label: "Flag", Icon: Flag },
  ball: { label: "Ball", Icon: Volleyball },
  exercise: { label: "Exercise", Icon: Dumbbell },
  bike: { label: "Bike ride", Icon: Bike },
  footprints: { label: "Walk", Icon: Footprints },
  tent: { label: "Camping", Icon: Tent },
  compass: { label: "Compass", Icon: Compass },
  map: { label: "Map", Icon: Map },

  // Getting around
  rocket: { label: "Rocket", Icon: Rocket },
  plane: { label: "Plane", Icon: Plane },
  sailboat: { label: "Sailboat", Icon: Sailboat },
  ship: { label: "Ship", Icon: Ship },
  train: { label: "Train", Icon: TrainFront },
  bus: { label: "Bus", Icon: Bus },
  car: { label: "Car", Icon: Car },
  truck: { label: "Truck", Icon: Truck },
  tractor: { label: "Tractor", Icon: Tractor },
  anchor: { label: "Anchor", Icon: Anchor },
  umbrella: { label: "Umbrella", Icon: Umbrella },
  outing: { label: "Outing", Icon: MapPin },

  // Rewards, money & tech
  gift: { label: "Gift", Icon: Gift },
  ticket: { label: "Ticket", Icon: Ticket },
  coins: { label: "Allowance", Icon: Coins },
  money: { label: "Cash", Icon: Banknote },
  piggybank: { label: "Savings", Icon: PiggyBank },
  dollar: { label: "Dollar", Icon: DollarSign },
  card: { label: "Card", Icon: CreditCard },
  wallet: { label: "Wallet", Icon: Wallet },
  tv: { label: "TV time", Icon: Tv },
  phone: { label: "Phone time", Icon: Smartphone },
  tablet: { label: "Tablet time", Icon: Tablet },
  laptop: { label: "Laptop", Icon: Laptop },
  watch: { label: "Watch", Icon: Watch },
  camera: { label: "Camera", Icon: Camera },
  screentime: { label: "Screen time", Icon: Clock },
  clock: { label: "Clock", Icon: Clock },
  timer: { label: "Timer", Icon: Timer },
  hourglass: { label: "Hourglass", Icon: Hourglass },
  calendar: { label: "Calendar", Icon: CalendarDays },
  bell: { label: "Bell", Icon: Bell },
  mail: { label: "Mail", Icon: Mail },
  message: { label: "Message", Icon: MessageCircle },
  image: { label: "Picture", Icon: Image },
  video: { label: "Video", Icon: Video },
  sticker: { label: "Sticker", Icon: Sticker },
  shapes: { label: "Shapes", Icon: Shapes },

  // Extras
  heart: { label: "Heart", Icon: Heart },
  crown: { label: "Crown", Icon: Crown },
  helping: { label: "Help out", Icon: HandHelping },
  handshake: { label: "Handshake", Icon: Handshake },

  // Expanded library
  happy: { label: "Big smile", Icon: SmilePlus },
  meh: { label: "Meh", Icon: Meh },
  twinkle: { label: "Twinkle", Icon: Sparkle },
  standing: { label: "Standing", Icon: PersonStanding },
  fishtwo: { label: "Fish", Icon: FishSymbol },
  origami: { label: "Paper crane", Icon: Origami },
  rain: { label: "Rain", Icon: CloudRain },
  snow: { label: "Snow", Icon: CloudSnow },
  storm: { label: "Storm", Icon: CloudLightning },
  drizzle: { label: "Drizzle", Icon: CloudDrizzle },
  fog: { label: "Fog", Icon: CloudFog },
  wind: { label: "Windy", Icon: Wind },
  tornado: { label: "Tornado", Icon: Tornado },
  sunrise: { label: "Sunrise", Icon: Sunrise },
  sunset: { label: "Sunset", Icon: Sunset },
  moonstar: { label: "Night", Icon: MoonStar },
  earth: { label: "Earth", Icon: Earth },
  flowertwo: { label: "Flower", Icon: Flower },
  beef: { label: "Steak", Icon: Beef },
  ham: { label: "Ham", Icon: Ham },
  lollipop: { label: "Lollipop", Icon: Lollipop },
  dessert: { label: "Pudding", Icon: Dessert },
  bean: { label: "Beans", Icon: Bean },
  nut: { label: "Nut", Icon: Nut },
  eggfried: { label: "Fried egg", Icon: EggFried },
  water: { label: "Water", Icon: GlassWater },
  honey: { label: "Honey", Icon: Hexagon },
  bookmark: { label: "Bookmark", Icon: Bookmark },
  bookstack: { label: "Books", Icon: BookCopy },
  filetext: { label: "Worksheet", Icon: FileText },
  pencilruler: { label: "Drafting", Icon: PencilRuler },
  eraser: { label: "Eraser", Icon: Eraser },
  highlighter: { label: "Highlighter", Icon: Highlighter },
  stamp: { label: "Stamp", Icon: Stamp },
  pentool: { label: "Design", Icon: PenTool },
  sigma: { label: "Sum", Icon: Sigma },
  pi: { label: "Pi", Icon: Pi },
  beaker: { label: "Beaker", Icon: Beaker },
  testtube: { label: "Test tube", Icon: TestTube },
  dna: { label: "DNA", Icon: Dna },
  magnet: { label: "Magnet", Icon: Magnet },
  orbit: { label: "Orbit", Icon: Orbit },
  binary: { label: "Code", Icon: Binary },
  speaker: { label: "Speaker", Icon: Speaker },
  disc: { label: "Record", Icon: Disc3 },
  audio: { label: "Audio", Icon: AudioLines },
  clef: { label: "Melody", Icon: Music2 },
  spelling: { label: "Spelling", Icon: SpellCheck },
  armchair: { label: "Armchair", Icon: Armchair },
  fan: { label: "Fan", Icon: Fan },
  thermo: { label: "Thermometer", Icon: Thermometer },
  spray: { label: "Spray clean", Icon: SprayCan },
  roller: { label: "Paint roller", Icon: PaintRoller },
  pickaxe: { label: "Pickaxe", Icon: Pickaxe },
  construction: { label: "Construction", Icon: Construction },
  hardhat: { label: "Hard hat", Icon: HardHat },
  battery: { label: "Battery", Icon: BatteryFull },
  blinds: { label: "Blinds", Icon: Blinds },
  doorclosed: { label: "Close door", Icon: DoorClosed },
  keyround: { label: "Key", Icon: KeyRound },
  window: { label: "Windows", Icon: Grid2x2 },
  nut2: { label: "Bolt", Icon: Bolt },
  goal: { label: "Goal", Icon: Goal },
  shield: { label: "Shield", Icon: Shield },
  sword: { label: "Sword", Icon: Sword },
  swords: { label: "Battle", Icon: Swords },
  castle: { label: "Castle", Icon: Castle },
  crosshair: { label: "Aim", Icon: Crosshair },
  gamepad: { label: "Gamepad", Icon: Gamepad },
  spade: { label: "Cards", Icon: Spade },
  club: { label: "Clubs", Icon: Club },
  bomb: { label: "Bomb", Icon: Bomb },
  wand: { label: "Magic", Icon: Wand },
  paperplane: { label: "Paper plane", Icon: Send },
  ferriswheel: { label: "Fair", Icon: FerrisWheel },
  carfront: { label: "Car", Icon: CarFront },
  taxi: { label: "Taxi", Icon: CarTaxiFront },
  ambulance: { label: "Ambulance", Icon: Ambulance },
  caravan: { label: "Caravan", Icon: Caravan },
  forklift: { label: "Forklift", Icon: Forklift },
  busfront: { label: "Bus", Icon: BusFront },
  tram: { label: "Tram", Icon: TramFront },
  takeoff: { label: "Takeoff", Icon: PlaneTakeoff },
  fuel: { label: "Fuel", Icon: Fuel },
  cone: { label: "Cone", Icon: TrafficCone },
  traintrack: { label: "Tracks", Icon: TrainTrack },
  monitor: { label: "Monitor", Icon: Monitor },
  monitorplay: { label: "Watch", Icon: MonitorPlay },
  disc2: { label: "Disc", Icon: Disc },
  printer: { label: "Printer", Icon: Printer },
  mouse: { label: "Mouse", Icon: Mouse },
  keyboard: { label: "Keyboard", Icon: Keyboard },
  wifi: { label: "Wifi", Icon: Wifi },
  megaphone: { label: "Megaphone", Icon: Megaphone },
  thumbsdown: { label: "Thumbs down", Icon: ThumbsDown },
  checkbig: { label: "Done", Icon: CircleCheckBig },
  starhalf: { label: "Half star", Icon: StarHalf },
  infinity: { label: "Infinity", Icon: InfinityIcon },
  hash: { label: "Number", Icon: Hash },
  at: { label: "At", Icon: AtSign },
  lock: { label: "Lock", Icon: Lock },
  unlock: { label: "Unlock", Icon: LockOpen },
};

export function getIcon(key: string): LucideIcon {
  return ICONS[key]?.Icon ?? HelpCircle;
}

export function iconLabel(key: string): string {
  return ICONS[key]?.label ?? "Icon";
}

export interface IconOption {
  key: string;
  label: string;
  Icon: LucideIcon;
}

export function iconOptions(keys: readonly string[]): IconOption[] {
  return keys.map((key) => ({
    key,
    label: iconLabel(key),
    Icon: getIcon(key),
  }));
}

/** Render a stored icon key. Decorative by default (aria-hidden). */
export function IconByName({
  name,
  size = 24,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  return createElement(getIcon(name), {
    size,
    className,
    "aria-hidden": true,
  });
}
