/**
 * The single, shared icon library. Every icon picker in the app (kid/parent
 * avatars, chores, rewards) draws from this one comprehensive set so the choices
 * are identical everywhere. Keys are stored as short strings in the
 * `people.avatar` and `chores.emoji` / `rewards.emoji` columns and rendered via
 * the Lucide registry in `components/icons/registry`.
 *
 * This module is pure data (no React/lucide) so it can be imported by validation
 * without bloating server bundles. Every key here must have a matching entry in
 * the registry — a unit test enforces it.
 *
 * Order is grouped by theme purely for how the picker reads; keys are never
 * renamed (stored values must keep resolving), only added.
 */

export const ICON_KEYS = [
  // People & faces
  "person",
  "people",
  "smile",
  "laugh",
  "thumbsup",
  "wave",
  "baby",
  "glasses",
  "drama",
  "robot",
  "ghost",
  "skull",
  "magic",
  "party",
  // Animals
  "cat",
  "dog",
  "rabbit",
  "bird",
  "fish",
  "turtle",
  "squirrel",
  "snail",
  "panda",
  "paw",
  "pet",
  "bug",
  "worm",
  "rat",
  "bone",
  "shell",
  "feather",
  // Nature & weather
  "sun",
  "cloudsun",
  "moon",
  "star",
  "sparkles",
  "rainbow",
  "cloud",
  "snowflake",
  "flame",
  "zap",
  "droplet",
  "waves",
  "mountain",
  "mountainsnow",
  "tree",
  "pine",
  "trees",
  "palm",
  "flower",
  "leaf",
  "clover",
  "sprout",
  "gem",
  "diamond",
  // Food & treats
  "apple",
  "cherry",
  "grape",
  "banana",
  "carrot",
  "citrus",
  "wheat",
  "egg",
  "salad",
  "soup",
  "sandwich",
  "hamburger",
  "pizza",
  "drumstick",
  "icecream",
  "icecream2",
  "candy",
  "candycane",
  "cookie",
  "cake",
  "cakeslice",
  "donut",
  "croissant",
  "popcorn",
  "milk",
  "cocoa",
  "soda",
  // Home & chores
  "bed",
  "beddouble",
  "alarm",
  "bath",
  "shower",
  "dishes",
  "cook",
  "groceries",
  "shopbag",
  "store",
  "trash",
  "recycle",
  "clean",
  "paint",
  "laundry",
  "washer",
  "tidy",
  "lamp",
  "desklamp",
  "lightbulb",
  "plug",
  "plants",
  "yard",
  "fix",
  "build",
  "drill",
  "shovel",
  "axe",
  "key",
  "door",
  "fridge",
  "microwave",
  // School & creative
  "backpack",
  "book",
  "library",
  "homework",
  "pen",
  "notes",
  "notebook",
  "study",
  "math",
  "science",
  "atom",
  "microscope",
  "telescope",
  "languages",
  "globe",
  "palette",
  "ruler",
  "scissors",
  "music",
  "guitar",
  "piano",
  "drum",
  "mic",
  "radio",
  "headphones",
  "movie",
  "clapperboard",
  // Play & sports
  "game",
  "joystick",
  "dice",
  "puzzle",
  "trophy",
  "medal",
  "award",
  "target",
  "flag",
  "ball",
  "exercise",
  "bike",
  "footprints",
  "tent",
  "compass",
  "map",
  // Getting around
  "rocket",
  "plane",
  "sailboat",
  "ship",
  "train",
  "bus",
  "car",
  "truck",
  "tractor",
  "anchor",
  "umbrella",
  "outing",
  // Rewards, money & tech
  "gift",
  "ticket",
  "coins",
  "money",
  "piggybank",
  "dollar",
  "card",
  "wallet",
  "tv",
  "phone",
  "tablet",
  "laptop",
  "watch",
  "camera",
  "screentime",
  "clock",
  "timer",
  "hourglass",
  "calendar",
  "bell",
  "mail",
  "message",
  "image",
  "video",
  "sticker",
  "shapes",
  // Extras
  "heart",
  "crown",
  "helping",
  "handshake",
] as const;

/**
 * Per-context aliases. All pickers share the same comprehensive set; only the
 * default selection differs by context.
 */
export const AVATAR_ICON_KEYS = ICON_KEYS;
export const CHORE_ICON_KEYS = ICON_KEYS;
export const REWARD_ICON_KEYS = ICON_KEYS;

export const DEFAULT_AVATAR_ICON = "smile";
/** Parents default to a neutral person icon (they don't pick an avatar). */
export const DEFAULT_PARENT_AVATAR_ICON = "person";
export const DEFAULT_CHORE_ICON = "star";
export const DEFAULT_REWARD_ICON = "gift";

/** All valid icon keys (the whole shared library). */
export const ALL_ICON_KEYS: readonly string[] = ICON_KEYS;

export function isIconKey(value: unknown): value is string {
  return typeof value === "string" && ALL_ICON_KEYS.includes(value);
}
